#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=./:~/bin:~/bin/eclipse:~/bin/mongodb/bin:/opt/local/bin:/opt/local/sbin:~/.rvm/bin:$PATH

##################
##     ALIAS    ##
##################

# aliasing platform specific binaries
if [[ "$(uname)" == "Linux" ]]; then
    alias ls='ls --color=auto'
    alias g="gvim --remote-silent"
    alias open="gnome-open"
elif [[ "$(uname)" == "Darwin" ]]; then
    alias ls='/usr/local/bin/gls --color=auto'
    alias find='gfind'
    alias g="mvim --remote-silent"
fi

## Standard aliases - security
# "-i" asks for confirmation when deleting. This is good.
# In the "dangerous" section there are aliases for non-confirmation.
alias rm='rm -v -i'
alias cp='cp -v -i'
alias mv='mv -v -i'

## Standard aliases - CPM/MSDOS heritage
alias del='rm -v -i'
alias cls='clear'
# "-p" lets you create a path structure with one command, ex. mkdir -p /a/b/c
alias md='mkdir -v -p'
alias rd='rmdir -v'

## Standard aliases - convenience
# To be used as in "cp /etc/inetd.conf /etc/inetd.conf.`today`"
alias today="date '+%d%h%y'"
# Pressing "x" and enter exits.
alias x='exit'
# Quite handy, type "ff test.c" to find "test.c".
# Keep in mind that there is also "locate test.c" which is faster.
alias ff='find . -name $*'
# Alias for "." and ".."
# Shows current directory
alias .='pwd'
# Goes back one directory
alias ..='cd ..'
alias ../='cd ../'
# Goes back two directories
alias ...='cd ../..'
alias .../='cd ../../'
# Goes to the root directory
alias /='cd /'

alias up='cd ..'
alias up2='cd ../..'
alias up3='cd ../../..'
alias up4='cd ../../../..'
alias up5='cd ../../../../..'
alias up6='cd ../../../../../..'
alias up7='cd ../../../../../../..'

## Standard aliases - for typos
# These are the most common typos made by users, even experienced ones.
# Send me yours.
alias maek='make'
alias alais='alias'
alias csl='clear'
alias sl='ls'

#allow grep and less to have color
alias grep='grep --color=auto -i'
alias less='less -R'

#use less
alias more='less -R'

#use vim
alias vi="vim"

#Standard ls commands
#list all .* files
alias l.='ls -d .*'
alias la='ls -a'
alias ll='ls -l'
alias lal='ls -al'

#aptget
alias ai='sudo apt-get install'

alias gru='git remote update'
alias grm='git rebase origin/master'
alias gittouch='git commit --amend --date="$(date)"'

alias h='history 0 | tail -25'
alias history='history 0'

function fgrep {
  find . -name "$1" -exec grep "$2" /dev/null {} \;
}

#####
bindkey "jj" vi-cmd-mode # map jj to go back to command mode
bindkey "^r" history-incremental-search-backward
bindkey "^f" history-incremental-search-forward

export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=~/git
source /usr/local/bin/virtualenvwrapper.sh
